alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
functions:
- github:
    branch: main
    deploy_on_push: true
    repo: audiomate-io/whisper-serverless
  name: transcribe-api
  routes:
  - path: /
  source_dir: /
name: transcribe
